FROM docker:dind

RUN apk add --no-cache curl bash jq unzip

ARG KIND_VERSION=0.30.0
RUN curl -Lo /usr/local/bin/kind "https://kind.sigs.k8s.io/dl/v${KIND_VERSION}/kind-linux-amd64" \
  && chmod +x /usr/local/bin/kind

ARG KUBECTL_VERSION=1.34.2
RUN curl -LO "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl" \
  && chmod +x kubectl \
  && mv kubectl /usr/local/bin/kubectl

ARG HELM_VERSION=4.0.1
RUN curl -fsSL "https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz" | tar xz \
  && mv linux-amd64/helm /usr/local/bin/helm \
  && chmod +x /usr/local/bin/helm \
  && rm -rf linux-amd64

ARG TERRAFORM_VERSION=1.12.1
RUN curl -fsSL "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -o /tmp/terraform.zip \
  && unzip /tmp/terraform.zip -d /usr/local/bin/ \
  && chmod +x /usr/local/bin/terraform \
  && rm /tmp/terraform.zip

ARG TERRAGRUNT_VERSION=0.93.12
RUN curl -fsSL "https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64" -o /usr/local/bin/terragrunt \
  && chmod +x /usr/local/bin/terragrunt

ARG JUST_VERSION=1.43.1
RUN curl -fsSL "https://github.com/casey/just/releases/download/${JUST_VERSION}/just-${JUST_VERSION}-x86_64-unknown-linux-musl.tar.gz" | tar xz -C /usr/local/bin just

ARG CRANE_VERSION=0.20.3
RUN curl -fsSL "https://github.com/google/go-containerregistry/releases/download/v${CRANE_VERSION}/go-containerregistry_Linux_x86_64.tar.gz" | tar xz -C /usr/local/bin crane

RUN mkdir /local
COPY local/k8s/ /local/k8s/
RUN ln -sf /local/k8s/.bashrc /root/.bashrc
COPY local/tf/ /local/tf/
COPY local/justfile /


ENV KIND_CLUSTER_NAME=${KIND_CLUSTER_NAME}
ENV KUBECTL_VERSION=${KUBECTL_VERSION}
ENV HELM_VERSION=${HELM_VERSION}
ENV TERRAFORM_VERSION=${TERRAFORM_VERSION}
ENV LOCAL_BIN_DIR=/local/bin
ENV KUBECONFIG=/generated/original_kubeconfig.yaml
